weather_path = "sample data/weather/"
generator_path = "sample data/generator/"
kriging_path = "sample data/kriging/"
estimation_path = "sample data/estimation/"
estimate_result_path = "sample data/estimation/results/"   
satellite_path ="sample data/satellite/900/"