weather_path = "D:/khnp_solar_power/sample data/weather/"
generator_path = "D:/khnp_solar_power/sample data/generator/"
kriging_path = "D:/khnp_solar_power/kriging/"
estimation_path = "D:/khnp_solar_power/estimation/"
estimate_result_path = "D:/khnp_solar_power/estimation/results/"   
satellite_path ="D:/khnp_solar_power/sample data/size900/"
